tukcom2023CD/RISING

backend/build.gradle

- build.gradle에 jib 코드 추가
</br>
</br>
"hlhl/jib-rising" 이 이름을 이미지 이름으로 사용하면 됩니다.
</br>
</br>

chore: backend jib 파일 추가

---

frontend/Dockerfile

배포를 위한 프론트 Dockerfile 설정
</br>
</br>
</br>
</br>

[chore/#4] 배포 환경 구축

---

backend/build.gradle
backend/src/main/java/com/rising/backend/domain/comment/domain/Comment.java
backend/src/main/java/com/rising/backend/domain/post/domain/Post.java
backend/src/main/java/com/rising/backend/domain/post/domain/PostType.java
backend/src/main/java/com/rising/backend/domain/user/domain/User.java
backend/src/main/java/com/rising/backend/global/config/SecurityConfig.java
backend/src/main/java/com/rising/backend/global/config/SwaggerConfig.java
backend/src/main/java/com/rising/backend/global/domain/BaseEntity.java
backend/src/main/java/com/rising/backend/global/util/SwaggerRedirector.java

Entity 파일 추가(BaseEntity, Post, User, Comment...), SwaggerConfig 추가
</br>
</br>
swaggerURL = /api/v1/docs
</br>
</br>

chore: Entity 세팅, Swagger 세팅

---

backend/src/main/java/com/rising/backend/BackendApplication.java
backend/src/main/java/com/rising/backend/domain/user/controller/UserController.java
backend/src/main/java/com/rising/backend/domain/user/domain/User.java
backend/src/main/java/com/rising/backend/domain/user/dto/mapper/UserMapper.java
backend/src/main/java/com/rising/backend/domain/user/dto/request/UserCreateRequestDto.java
backend/src/main/java/com/rising/backend/domain/user/repository/UserRepository.java
backend/src/main/java/com/rising/backend/domain/user/service/UserService.java
backend/src/main/java/com/rising/backend/global/config/SecurityConfig.java

user 도메인 관련 파일 생성 및 user create API 초안 구현
</br>
</br>
</br>
</br>

feat: user create API 구현

---

backend/src/main/java/com/rising/backend/domain/post/domain/Post.java
backend/src/main/resources/application.yml
docker-compose.yml

말 그대로 도커 오류 해결했습니다.. 
</br>
</br>
</br>
</br>

fix: 도커 오류 해결

---

frontend/package-lock.json
frontend/package.json
frontend/src/App.tsx
frontend/src/components/Btn.tsx
frontend/src/components/Index/AnsTitleIndex.tsx
frontend/src/components/Index/EndIndex.tsx
frontend/src/components/Index/KeywordIndex.tsx
frontend/src/components/Index/QuesTitleIndex.tsx
frontend/src/components/MentoNavBar.tsx
frontend/src/components/NavBar.tsx
frontend/src/components/QuesNavBar.tsx
frontend/src/components/Select/KeywordSelect.tsx
frontend/src/components/Select/data.ts
frontend/src/page/AnsPage.tsx
frontend/src/page/PrivateAnsCheckPage.tsx
frontend/src/page/PrivateAnsPage.tsx
frontend/src/page/PrivateQuesPage.tsx
frontend/src/page/QuesPage.tsx

질문 작성 페이지, 과외 질문 작성 페이지 퍼블리싱 완료
버튼 클릭시 페이지 이동 구현완료(질문리스트로 이동, 각 페이지에서 버튼 클릭시 메인페이지로 이동)
</br>
</br>
</br>
</br>

[FE/feat/#43] 질문 작성 페이지, 과외 질문 작성 페이지 퍼블리싱

---

frontend/.eslintrc.js
frontend/package-lock.json
frontend/package.json
frontend/src/components/Btn.tsx
frontend/src/components/Index/AnsTitleIndex.tsx
frontend/src/components/Ques.tsx
frontend/src/components/Select/FrameWorkSelect.tsx
frontend/src/components/Select/KeywordData.ts
frontend/src/components/Select/KeywordSelect.tsx
frontend/src/components/Select/LanguageSelect.tsx
frontend/src/components/Select/OptionSelect.tsx
frontend/src/components/Select/QuesData.ts
frontend/src/components/Tag.tsx
frontend/src/page/AnsPage.tsx
frontend/src/page/PrivateAnsCheckPage.tsx
frontend/src/page/PrivateAnsPage.tsx
frontend/src/page/QuesListPage.tsx
frontend/tailwind.config.js

질문 리스트 페이지 퍼블리싱 완료
</br>
</br>
피그마 초안 디자인과 달리 select를 활용하여 퍼블리싱 진행하였습니다.
</br>
</br>

[FE/feat/#37] 질문 리스트 페이지 퍼블리싱

---

backend/build.gradle
backend/src/main/java/com/rising/backend/domain/sharecoding/controller/CodeController.java
backend/src/main/java/com/rising/backend/domain/sharecoding/domain/Act.java
backend/src/main/java/com/rising/backend/domain/sharecoding/domain/Operation.java
backend/src/main/java/com/rising/backend/global/config/RabbitConfig.java
backend/src/main/java/com/rising/backend/global/config/StompConfig.java
backend/src/main/java/com/rising/backend/global/constant/RabbitMQ.java

RabbitMQ 사용을 위한 세팅을 하였습니다.
- CodeController: Websocket, RabbitMQ를 사용하여 메시징
- Operation: 주고 받는 데이터 (일단 라인 넘버랑, 텍스트 추가)
- RabbitConfig, StompConfig: 설정 파일들
</br>
</br>
웹소켓 연결을 test해보고 싶다면 StompConfig파일에서 line16 사용, 프론트엔드와 연결할 때는 line15 사용
registry.addEndpoint("/stomp").setAllowedOriginPatterns("*"); <- line 16
</br>
</br>

[BE/chore/#40] RabbitMQ 세팅

---

backend/src/main/java/com/rising/backend/domain/post/controller/PostController.java
backend/src/main/java/com/rising/backend/domain/post/dto/PostDto.java
backend/src/main/java/com/rising/backend/domain/post/mapper/PostMapper.java
backend/src/main/java/com/rising/backend/domain/post/service/PostService.java
backend/src/main/java/com/rising/backend/global/result/ResultCode.java

- PostController에 질문 리스트를 페이징해서 불러오는 API를 구현했습니다.
</br>
</br>
</br>
</br>

[BE/feat/#53] : 질문 리스트 페이징 구현

---

backend/src/main/java/com/rising/backend/domain/post/controller/PostController.java
backend/src/main/java/com/rising/backend/domain/post/domain/Session.java
backend/src/main/java/com/rising/backend/domain/post/dto/PostDto.java
backend/src/main/java/com/rising/backend/domain/post/mapper/PostMapper.java
backend/src/main/java/com/rising/backend/domain/post/service/PostService.java
backend/src/main/java/com/rising/backend/global/result/ResultCode.java
backend/src/main/java/com/rising/backend/global/util/UuidConverter.java

postId로 post 조회하는 api 구현
</br>
</br>
</br>
</br>

[Be/feat/#57] Post id로 Post 조회 api 구현

---

backend/src/main/java/com/rising/backend/domain/post/controller/PostController.java
backend/src/main/java/com/rising/backend/domain/post/domain/Post.java
backend/src/main/java/com/rising/backend/domain/post/mapper/PostMapper.java
backend/src/main/java/com/rising/backend/domain/post/repository/PostRepository.java
backend/src/main/java/com/rising/backend/domain/post/service/PostService.java
backend/src/main/java/com/rising/backend/global/result/ResultCode.java
backend/src/main/resources/application.yml
docker-compose.yml

- 엔티티의 memo 칼럼 삭제
- docker-compose mysql버전 변경
- hibernate설정 변경
- userId로 작성한 게시글 목록 조회
</br>
</br>
</br>
</br>

[BE/feat/#59] userId로 post list 조회 및 memo 삭제

---

backend/src/main/java/com/rising/backend/domain/chat/controller/WebSocketChatController.java
backend/src/main/java/com/rising/backend/domain/sharecoding/controller/CodeController.java
backend/src/main/java/com/rising/backend/domain/user/controller/UserController.java
backend/src/main/java/com/rising/backend/global/config/RabbitConfig.java
backend/src/main/java/com/rising/backend/global/result/ResultCode.java
frontend/src/page/MentoringPage.tsx

- 테스트용 백엔드 로직 작성
</br>
</br>
- postId를 1로 설정하여 테스트
</br>
</br>

[BE/feat/#69] 코드 에디터 테스트를 위한 로직 작성

---

backend/src/main/java/com/rising/backend/domain/sharecoding/domain/Operation.java
frontend/src/page/AnsPage.tsx
frontend/src/page/MentoringPage.tsx
frontend/src/page/PrivateAnsCheckPage.tsx
frontend/src/page/PrivateAnsPage.tsx
frontend/src/page/PrivateQuesPage.tsx
frontend/src/page/QuesChatPage.tsx

과외 질문 확인 페이지, 멘토링 페이지, 멘토링 이후 결과 확인 페이지 api 연결 
코드 에디터와 웹소켓 연결 완료
</br>
</br>
- 1번 채팅방으로만 설정된 상태
</br>
</br>

[FE/feat//#76] 과외 질문 상세 페이지

---

backend/src/main/java/com/rising/backend/domain/comment/repository/CommentRepository.java
backend/src/main/java/com/rising/backend/domain/post/dto/PostDto.java
backend/src/main/java/com/rising/backend/domain/post/mapper/PostMapper.java

제목과 같음
</br>
</br>
</br>
</br>

[BE/feat/#90] post 개별조회 Dto 작성날짜 추가, 전체조회 Dto 작성날짜 및 댓글수 추가

---

frontend/src/page/LoginPage.tsx
frontend/src/page/SignUpPage.tsx

로그인 및 회원가입 기능 구현 마무리
로그인 및 회원가입 과정에서 정상적으로 세션 발급 과정을 확인함
로그인 성공 과정에서 유효성 검증을 통한 메인페이지 라우팅 기능 구현
</br>
</br>
상태관리를 통한 인증방식이 아닌 로그인 회원가입 기능이라 추후에 버전 업그레이드 필요해 보임.
</br>
</br>

Fe/feat/#82 Session 방식을 활용한 로그인 및 회원가입 api 연동 구현

---

frontend/src/components/Ques.tsx
frontend/src/components/Select/KeyWordOptionSelect.tsx
frontend/src/components/Select/OptionSelect.tsx
frontend/src/components/Tags/Date.tsx
frontend/src/page/MentoringPage.tsx
frontend/src/page/PrivateAnsCheckPage.tsx
frontend/src/page/PrivateAnsPage.tsx
frontend/src/page/PrivateQuesPage.tsx
frontend/src/page/QuesChatPage.tsx
frontend/src/page/QuesListPage.tsx
frontend/src/page/QuesPage.tsx

페이지네이션 구현
질문제목이 밀리는 현상 수정
키워드 선택하기 전 분류 제목 확인할 수 있게 수정
</br>
</br>
</br>
</br>

[FE/feat/95] 질문 리스트 페이지 : 페이지네이션, ui 수정

---

backend/src/main/java/com/rising/backend/global/config/StompConfig.java
frontend/src/page/LoginPage.tsx
frontend/src/page/QuesListPage.tsx
frontend/src/page/SignUpPage.tsx

- stomp 호스트 설정 변경
</br>
</br>
</br>
</br>

chore: stompconfig 호스트설정

---

backend/src/main/java/com/rising/backend/domain/chat/controller/ChatRoomController.java
backend/src/main/java/com/rising/backend/domain/chat/repository/ChatRoomRepository.java
backend/src/main/java/com/rising/backend/domain/chat/service/ChatRoomService.java

[GET] `/api/v1/chatrooms/mentor`
현재 로그인된 user가 mentor인 채팅방 조회
</br>
</br>
</br>
</br>

[BE/feat/#107] 현재 로그인된 user가 mentor인 채팅방 조회

---

docker-compose.yml
grafana/dashboards/nginx-monitoring.json
grafana/datasource.yml
nginx/nginx.conf
prometheus/prometheus.yml
prometheus/rules.yml

- docker-compose.yml에 prometheus, node-exporter, grafana 추가
- grafana dashboard 파일 추가
- nginx.conf /metrics uri 추가
- prometheus.yml과 rules.yml 추가
</br>
</br>
</br>
</br>

[BE/feat/#104] 모니터링 프로그램 연동

---

frontend/src/components/Ans/Ans.tsx
frontend/src/page/AnsPage.tsx
frontend/src/page/QuesPage.tsx

일반 질문 답변 페이지 api 연결 구현
</br>
</br>
날짜 및 시간 api 연결 구현 미완성
다음 이슈에서 연결 예정
</br>
</br>

[FE/feat/#101] 일반 질문 <답변> 페이지 api 연동 구현

---

frontend/package-lock.json
frontend/package.json
frontend/src/components/Btn.tsx
frontend/src/components/Chat/MyMessage.tsx
frontend/src/components/Chat/OthersMessage.tsx
frontend/src/components/ChatBox.tsx
frontend/src/page/LoginPage.tsx
frontend/src/page/MentoringPage.tsx
frontend/src/page/MyPage.tsx
frontend/src/page/PrivateAnsCheckPage.tsx
frontend/src/page/PrivateAnsPage.tsx
frontend/src/page/PrivateQuesPage.tsx
frontend/src/page/QuesChatPage.tsx
frontend/src/page/SignUpPage.tsx

채팅방 페이지 멘토와 멘티 구분, ui 수정, 페이지 이동 시 로컬 스토리지 사용
</br>
</br>
</br>
</br>

[FE/feat/#99] 채팅방 페이지 멘토와 멘티 구분, ui 수정, 페이지 이동 시 로컬 스토리지 사용

---

frontend/src/components/Ans/Ans.tsx
frontend/src/page/AnsPage.tsx

댓글 작성 date, time 불러오기 구현 완료
</br>
</br>
</br>
</br>

[FE/feat/#118] 일반 질문 답변 페이지 날짜, 시간 api 연결

---

frontend/src/page/AfterMainPage.tsx
frontend/src/page/BeforeMainPage.tsx
frontend/src/utils/pageStyle.css
frontend/tailwind.config.js

메인페이지에 애니메이션 효과 추가했습니다.
</br>
</br>
</br>
</br>

[FE/feat/#128] 메인페이지 동적인 css 추가

---

frontend/src/components/NavBar/NavBar.tsx
frontend/src/components/NavBar/PrivateQuesNavBar.tsx
frontend/src/components/NavBar/QuesListNavBar.tsx
frontend/src/components/NavBar/QuesNavBar.tsx
frontend/src/page/AfterMainPage.tsx
frontend/src/page/BeforeMainPage.tsx
frontend/src/page/QuesPage.tsx
frontend/tailwind.config.js

로그인 전/후 메인페이지, 상단바, 질문작성 페이지 ui 깨진 부분 수정
</br>
</br>
</br>
</br>

[FE/feat/#130] 반응형 퍼블리싱, ui 수정

---

frontend/src/page/AnsPage.tsx

ansInfo 값을 newAnsInfo 값으로 할당시켜 useEffect 무한루프 해결
</br>
</br>
</br>
</br>

[FE/feat/#134] 댓글 useEffect 관련 랜더링 오류 해결

---

frontend/public/index.html
frontend/tailwind.config.js

tailwind css 사용하여 폰트 적용 완료 했습니다.
</br>
</br>
</br>
</br>

[FE/feat/#137] 폰트 적용

---

frontend/src/page/AnsPage.tsx
frontend/src/page/QuesPage.tsx

무한 요청이 발생하지 않게 수정
</br>
</br>
</br>
</br>

[FE/fix/#134] 댓글 작성 시 무한 요청 에러 해결

---

frontend/src/page/AnsPage.tsx
frontend/src/page/PrivateQuesPage.tsx
frontend/src/page/QuesPage.tsx

페이지 별 alert 알림 추가
</br>
</br>
</br>
</br>

[FE/feat/#138] 페이지 별 alert 알림 추가

---

frontend/src/page/PrivateAnsPage.tsx

툴팁으로 url을 보여주었던 방식 대신 링크 버튼 클릭시 클립보드 기능으로 바꿔서 구현
</br>
</br>
</br>
</br>

[FE/feat/#149] 링크 버튼 클립보드 기능 구현

---

frontend/src/components/Ans/Ans.tsx
frontend/src/components/Editor/EditorViewer.tsx
frontend/src/page/AnsPage.tsx
frontend/src/page/PrivateAnsPage.tsx
frontend/src/page/PrivateQuesPage.tsx
frontend/src/page/QuesPage.tsx

- 답변 페이지 질문 내용 박스 안에 꽉 차게 설정
- 글자 수 많을 시 스크롤 등장하도록 구현
- 댓글(답글) 글자 수 많을 시 박스 바깥으로 벗어나지 않도록 반응형 구현
- 프로필 이미지 동그랗게 수정
- 기타 컴포넌트 연동 반응형 수정
</br>
</br>
API 통신 진행하느라 axios 통신 부분 로컬 개발용으로 변경하였음
</br>
</br>

[FE/feat/#151] 인풋 박스 반응형 수정

---

backend/build.gradle
backend/src/main/java/com/rising/backend/domain/user/controller/UserController.java
backend/src/main/java/com/rising/backend/domain/user/service/LoginService.java
backend/src/main/java/com/rising/backend/global/interceptor/LoginInterceptor.java
backend/src/main/resources/application.yml

- 세션과 세션 attribute가 mysql에 저장되도록 변경
</br>
</br>
</br>
</br>

[BE/feat/#153] 세션 로그인 - 세션 저장 방식 mysql에 저장하도록 변경

---

backend/src/main/java/com/rising/backend/global/error/ErrorCode.java
backend/src/main/java/com/rising/backend/global/error/ErrorResponse.java
backend/src/main/java/com/rising/backend/global/error/GlobalExceptionHandler.java
backend/src/main/java/com/rising/backend/global/error/exception/BusinessException.java
backend/src/main/java/com/rising/backend/global/exception/BusinessException.java

- BusinessException에 코드 추가
- ErrorCode Enum 추가
- ErrorResponse, GlobalExceptionHandler 추가
</br>
</br>
- 예외 처리 방법 잘 모르겠으면 저한테 문의주세요
</br>
</br>

[BE/feat/#161] ErrorResponse 적용

---

backend/Dockerfile
backend/build.gradle
backend/src/main/java/com/rising/backend/global/config/StompConfig.java
docker-compose.yml

- build.gradle 파일 내 jib 설정 삭제
- docker-compose backend 컨테이너 수정
- backend Dockerfile 추가
</br>
</br>
- Docker 실행 전 Spring Boot build 파일이 존재해야 합니다~
</br>
</br>

fix: Backend docker build 수정

---

frontend/src/page/MentoringPage.tsx

코드에디터 충돌 방지 구현
코드에디터 반응형 구현
</br>
</br>
CRDT 알고리즘 미적용 --> 동시에 입력시 오류 발생
</br>
</br>

[FE/feat/#160] 코드에디터 충돌 방지 구현

---

backend/src/main/java/com/rising/backend/domain/comment/service/CommentService.java
backend/src/main/java/com/rising/backend/domain/post/service/PostService.java
backend/src/main/java/com/rising/backend/global/error/ErrorCode.java
backend/src/main/java/com/rising/backend/global/error/GlobalExceptionHandler.java
backend/src/main/java/com/rising/backend/global/error/exception/NotFoundException.java
backend/src/main/resources/application.yml

- NotFoundException 클래스 생성
- GlobalExceptionHandler에 NotFoundException 핸들러 추가
- 각 도메인 서비스에 예외처리하는 코드 작성
</br>
</br>
</br>
</br>

[BE/refactor/#170] post, comment 도메인 예외처리

---

docker-compose.yml
frontend/nginx.conf
init-letsencrypt.sh
nginx/init-letsencrypt.sh

- https적용
</br>
</br>
- 현재 메인페이지 제외 https리다이렉트 안되는 상태
</br>
</br>

[BE/chore/#167] https 적용

---

backend/src/main/java/com/rising/backend/domain/chat/exception/ChatRoomCreationFailedException.java
backend/src/main/java/com/rising/backend/domain/chat/exception/ChatRoomNotFoundException.java
backend/src/main/java/com/rising/backend/domain/chat/service/ChatMessageService.java
backend/src/main/java/com/rising/backend/domain/chat/service/ChatRoomService.java
backend/src/main/java/com/rising/backend/domain/user/controller/UserController.java
backend/src/main/java/com/rising/backend/domain/user/exception/DuplicatedUsernameException.java
backend/src/main/java/com/rising/backend/domain/user/exception/InvalidPasswordException.java
backend/src/main/java/com/rising/backend/domain/user/exception/LoginRequiredException.java
backend/src/main/java/com/rising/backend/domain/user/exception/UserNotFoundException.java
backend/src/main/java/com/rising/backend/domain/user/service/UserService.java
backend/src/main/java/com/rising/backend/global/error/ErrorCode.java
backend/src/main/java/com/rising/backend/global/interceptor/LoginInterceptor.java

- 채팅 및 유저 예외처리
</br>
</br>
</br>
</br>

[BE/feat/#173] 채팅 및 유저 예외처리

---

frontend/package-lock.json
frontend/package.json
frontend/src/page/MentoringPage.tsx

debounce를 사용하는 이유는 중복 실행을 방지하기 위함.
사용자가 입력을 완료하면 일정 시간 후에 이벤트 핸들러가 실행되어 웹소켓을 통해 한 번만 데이터를 전송하게 된다.
반응속도 100ms 로 설정
</br>
</br>
</br>
</br>

[FE/feat/#179] 크롬 브라우저 한글 중복입력 오류 해결

---

backend/src/main/java/com/rising/backend/domain/user/controller/UserController.java
backend/src/main/java/com/rising/backend/domain/user/dto/UserDto.java

response body에 로그인한 회원의 이름추가
</br>
</br>
</br>
</br>

[BE/feat/#183] login response body에 username추가

---

frontend/.eslintrc.js
frontend/package-lock.json
frontend/package.json
frontend/src/components/ChatBox.tsx
frontend/src/components/redux/store.tsx
frontend/src/components/redux/userSlice.tsx
frontend/src/index.tsx
frontend/src/page/AfterMainPage.tsx
frontend/src/page/LoginPage.tsx
frontend/src/page/MyPage.tsx
frontend/src/page/PrivateAnsPage.tsx
frontend/src/page/QuesChatPage.tsx
frontend/src/page/SignUpPage.tsx

- 일대일 채팅, 멘토가 채팅을 입력할 때 새로고침을 해야만 채팅이 보내지는 문제 해결
- redux toolkit 사용시 새로고침하면 저장된 데이터가 사라지는 문제를 redux-persist를 사용하여 해결
</br>
</br>
</br>
</br>

[FE/fix/#148] 채팅방 기능 안정화

---

frontend/package-lock.json
frontend/package.json
frontend/src/page/MentoringPage.tsx
frontend/src/page/PrivateAnsPage.tsx

코드 에디터 VScode 에디터 라이브러리인 monaco editor로 변경
멘토링 질문 게시글 불러올 때 첫 게시글만 불러오던 오류 해결
마우스 커서 오류 해결
언어별 구문 하이라이팅 적용
게시글에서 선택된 언어로 자동 언어 선택 기능
</br>
</br>
</br>
</br>

[FE/feat/#178] 코드 에디터 변경 및 오류 수정

---

.github/workflows/prod.workflow.yml

배포용 스크립트 작성
</br>
</br>
</br>
</br>

[chore/kjeongh-patch-1] Update prod.workflow.yml

---

frontend/package-lock.json
frontend/src/page/MyPage.tsx
frontend/src/page/PrivateAnsPage.tsx
frontend/src/page/QuesChatPage.tsx
frontend/src/page/QuesPage.tsx

채팅방의 무한스크롤 기능 구현했습니다.
</br>
</br>
</br>
</br>

[FE/feat/#139] 채팅방 무한스크롤 기능

---

frontend/package-lock.json
frontend/src/page/MyPage.tsx
frontend/src/page/PrivateAnsPage.tsx
frontend/src/page/QuesChatPage.tsx
frontend/src/page/QuesPage.tsx

무한스크롤 기능을 main에만 합쳐서 다시 디벨롭에 머지
</br>
</br>
</br>
</br>

[FE/feat/#139] 채팅방 무한스크롤

---

backend/build.gradle
backend/src/main/java/com/rising/backend/domain/sharecoding/controller/CodeController.java
backend/src/main/java/com/rising/backend/domain/sharecoding/dto/CodingDto.java
backend/src/main/java/com/rising/backend/domain/sharecoding/service/CodeService.java
backend/src/main/java/com/rising/backend/global/config/CompileConfig.java
backend/src/main/java/com/rising/backend/global/result/ResultCode.java

[BE/feat/#201] 컴파일러 API 구현

---

backend/src/main/java/com/rising/backend/domain/post/controller/PostController.java
backend/src/main/java/com/rising/backend/domain/post/dto/PostDto.java
backend/src/main/java/com/rising/backend/domain/post/mapper/PostMapper.java
backend/src/main/java/com/rising/backend/domain/post/service/PostService.java
frontend/src/components/Ques.tsx
frontend/src/page/AnsPage.tsx
frontend/src/page/MentoringPage.tsx
frontend/src/page/MyPage.tsx
frontend/src/page/PrivateAnsCheckPage.tsx
frontend/src/page/PrivateAnsPage.tsx
frontend/src/page/QuesListPage.tsx

멘토링이 된 게시물과 안된 게시물에 대한 라우팅 수정
멘토링이 완료되면 작성된 코드 보여주는 기능 구현
</br>
</br>
</br>
</br>

[FE/feat/#211] 멘토링 질문 답변

---

frontend/src/components/Select/OptionSelect.tsx
frontend/src/components/Select/QuesData.ts
frontend/src/page/QuesListPage.tsx
frontend/src/page/SignUpPage.tsx

게시물 필터링 기능 구현
페이지네이션 10개씩 진행
회원가입 유효성 검사 UX 수정
</br>
</br>
</br>
</br>

[FE/feat/#206] 게시물 필터링 기능 구현

---

frontend/src/page/MentoringPage.tsx
frontend/src/page/PrivateAnsPage.tsx

컴파일러 결과를 보여줄 퍼블리싱 작업 및 컴파일러 api 연결
컴파일러 api 연동 1차 구현 완료
컴파일러 결과창 스타일링 완료
언어 추가 완료
</br>
</br>
</br>
</br>

[FE/feat/#200] 컴파일러 결과 보여줄 퍼블리싱 및 api 연결

---

backend/src/main/java/com/rising/backend/domain/post/controller/PostController.java

- request body 추가
</br>
</br>
</br>
</br>

#216: solvedcode내용 추가

---

frontend/src/components/Editor/ToastEditor.tsx
frontend/src/components/redux/userSlice.tsx
frontend/src/page/AfterMainPage.tsx
frontend/src/page/AnsPage.tsx
frontend/src/page/LoginPage.tsx
frontend/src/page/MentoringPage.tsx
frontend/src/page/MyPage.tsx
frontend/src/page/PrivateAnsCheckPage.tsx
frontend/src/page/PrivateAnsPage.tsx

- userid를 redux에 저장
- 본인이 작성한 글만 수정 및 삭제
- 마이페이지에서 내 질문 -> 내 채팅방 -> 내가 멘토인 채팅방으로 순서 변경
- 메인페이지의 내 채팅방 이름을 마이페이지로 수정
</br>
</br>
</br>
</br>

[FE/feat/#210] 글 수정, 삭제

---

frontend/src/page/MentoringPage.tsx

typing : true
typing : false
웹소켓 통신을 통한 타이핑 여부 추적
* 알림 기능 구현
1. 상대방이 입력중입니다.
2. 코드를 입력하세요.
3. 코드를 입력중입니다.
4. 브라우저의 입력이 3초간 없으면 타이핑 가능
* 블로킹 기능 구현
1. 소켓 서버에서 불러온 typing 여부를 통한 readonly 상태 관리
2. 다른 브라우저가 입력시 코드 에디터 입력 비활성화 기능 구현
</br>
</br>
</br>
</br>

[FE/feat/#225] 코드 에디터 블로킹 기능 최종 구현
